// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'cart_rule_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_CartRuleDTO _$CartRuleDTOFromJson(Map<String, dynamic> json) => _CartRuleDTO(
  id: (json['id'] as num?)?.toInt(),
  idCustomer: parseNullOrUnsignedId(json['id_customer']),
  dateFrom: parseIsDate(json['date_from']),
  dateTo: parseIsDate(json['date_to']),
  description: json['description'] as String?,
  quantity: parseNullOrUnsignedId(json['quantity']),
  quantityPerUser: parseNullOrUnsignedId(json['quantity_per_user']),
  priority: parseNullOrUnsignedId(json['priority']),
  partialUse: parseIsBool(json['partial_use']),
  code: json['code'] as String?,
  minimumAmount: parseIsFloat(json['minimum_amount']),
  minimumAmountTax: parseIsBool(json['minimum_amount_tax']),
  minimumAmountCurrency: parseIsInt(json['minimum_amount_currency']),
  minimumAmountShipping: parseIsBool(json['minimum_amount_shipping']),
  countryRestriction: parseIsBool(json['country_restriction']),
  carrierRestriction: parseIsBool(json['carrier_restriction']),
  groupRestriction: parseIsBool(json['group_restriction']),
  cartRuleRestriction: parseIsBool(json['cart_rule_restriction']),
  productRestriction: parseIsBool(json['product_restriction']),
  shopRestriction: parseIsBool(json['shop_restriction']),
  freeShipping: parseIsBool(json['free_shipping']),
  reductionPercent: parseIsFloat(json['reduction_percent']),
  reductionAmount: parseIsFloat(json['reduction_amount']),
  reductionTax: parseIsBool(json['reduction_tax']),
  reductionCurrency: parseNullOrUnsignedId(json['reduction_currency']),
  reductionProduct: parseIsInt(json['reduction_product']),
  reductionExcludeSpecial: parseIsBool(json['reduction_exclude_special']),
  giftProduct: parseNullOrUnsignedId(json['gift_product']),
  giftProductAttribute: parseNullOrUnsignedId(json['gift_product_attribute']),
  highlight: parseIsBool(json['highlight']),
  active: parseIsBool(json['active']),
  dateAdd: parseIsDate(json['date_add']),
  dateUpd: parseIsDate(json['date_upd']),
  name: json['name'] as String?,
);

Map<String, dynamic> _$CartRuleDTOToJson(
  _CartRuleDTO instance,
) => <String, dynamic>{
  'id': instance.id,
  'id_customer': instance.idCustomer,
  'date_from': isDateToJson(instance.dateFrom),
  'date_to': isDateToJson(instance.dateTo),
  'description': instance.description,
  'quantity': instance.quantity,
  'quantity_per_user': instance.quantityPerUser,
  'priority': instance.priority,
  'partial_use': isBoolToJson(instance.partialUse),
  'code': instance.code,
  'minimum_amount': isFloatToJson(instance.minimumAmount),
  'minimum_amount_tax': isBoolToJson(instance.minimumAmountTax),
  'minimum_amount_currency': isIntToJson(instance.minimumAmountCurrency),
  'minimum_amount_shipping': isBoolToJson(instance.minimumAmountShipping),
  'country_restriction': isBoolToJson(instance.countryRestriction),
  'carrier_restriction': isBoolToJson(instance.carrierRestriction),
  'group_restriction': isBoolToJson(instance.groupRestriction),
  'cart_rule_restriction': isBoolToJson(instance.cartRuleRestriction),
  'product_restriction': isBoolToJson(instance.productRestriction),
  'shop_restriction': isBoolToJson(instance.shopRestriction),
  'free_shipping': isBoolToJson(instance.freeShipping),
  'reduction_percent': isFloatToJson(instance.reductionPercent),
  'reduction_amount': isFloatToJson(instance.reductionAmount),
  'reduction_tax': isBoolToJson(instance.reductionTax),
  'reduction_currency': instance.reductionCurrency,
  'reduction_product': isIntToJson(instance.reductionProduct),
  'reduction_exclude_special': isBoolToJson(instance.reductionExcludeSpecial),
  'gift_product': instance.giftProduct,
  'gift_product_attribute': instance.giftProductAttribute,
  'highlight': isBoolToJson(instance.highlight),
  'active': isBoolToJson(instance.active),
  'date_add': isDateToJson(instance.dateAdd),
  'date_upd': isDateToJson(instance.dateUpd),
  'name': instance.name,
};
