// Mocks generated by Mockito 5.4.6 from annotations
// in prestashop_api/test/product/product_prestashop_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prestashop_api/src/common/model/remote_response.dart' as _i2;
import 'package:prestashop_api/src/common/options/display/display.dart' as _i8;
import 'package:prestashop_api/src/common/options/filter/filter.dart' as _i6;
import 'package:prestashop_api/src/common/options/sort/sort.dart' as _i9;
import 'package:prestashop_api/src/common/options/sort/sort_field_order.dart'
    as _i10;
import 'package:prestashop_api/src/products/dto/product_output_dto.dart' as _i5;
import 'package:prestashop_api/src/products/network/product_data_source.dart'
    as _i3;
import 'package:prestashop_api/src/products/network/product_enums.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRemoteResponse_0<T> extends _i1.SmartFake
    implements _i2.RemoteResponse<T> {
  _FakeRemoteResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductDataSource extends _i1.Mock implements _i3.ProductDataSource {
  @override
  _i4.Future<_i2.RemoteResponse<_i5.ProductOutputDTO>> getProducts({
    required int? languageId,
    _i6.Filter<_i7.ProductFilterField>? filter,
    _i8.Display<_i7.ProductDisplayField>? display,
    _i9.Sort<_i10.SortFieldOrder<_i7.ProductSortField>>? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #languageId: languageId,
              #filter: filter,
              #display: display,
              #sort: sort,
            }),
            returnValue:
                _i4.Future<_i2.RemoteResponse<_i5.ProductOutputDTO>>.value(
                  _FakeRemoteResponse_0<_i5.ProductOutputDTO>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #languageId: languageId,
                      #filter: filter,
                      #display: display,
                      #sort: sort,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.RemoteResponse<_i5.ProductOutputDTO>>.value(
                  _FakeRemoteResponse_0<_i5.ProductOutputDTO>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #languageId: languageId,
                      #filter: filter,
                      #display: display,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.RemoteResponse<_i5.ProductOutputDTO>>);

  @override
  _i4.Future<_i2.RemoteResponse<_i5.ProductOutputDTO>> getProductsPage({
    required int? languageId,
    required int? page,
    required int? perPage,
    _i6.Filter<_i7.ProductFilterField>? filter,
    _i8.Display<_i7.ProductDisplayField>? display,
    _i9.Sort<_i10.SortFieldOrder<_i7.ProductSortField>>? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsPage, [], {
              #languageId: languageId,
              #page: page,
              #perPage: perPage,
              #filter: filter,
              #display: display,
              #sort: sort,
            }),
            returnValue:
                _i4.Future<_i2.RemoteResponse<_i5.ProductOutputDTO>>.value(
                  _FakeRemoteResponse_0<_i5.ProductOutputDTO>(
                    this,
                    Invocation.method(#getProductsPage, [], {
                      #languageId: languageId,
                      #page: page,
                      #perPage: perPage,
                      #filter: filter,
                      #display: display,
                      #sort: sort,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.RemoteResponse<_i5.ProductOutputDTO>>.value(
                  _FakeRemoteResponse_0<_i5.ProductOutputDTO>(
                    this,
                    Invocation.method(#getProductsPage, [], {
                      #languageId: languageId,
                      #page: page,
                      #perPage: perPage,
                      #filter: filter,
                      #display: display,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.RemoteResponse<_i5.ProductOutputDTO>>);
}
