// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_dto.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_ProductDTO _$ProductDTOFromJson(Map<String, dynamic> json) => _ProductDTO(
  id: (json['id'] as num?)?.toInt(),
  idManufacturer: parseUnsignedId(json['id_manufacturer']),
  idSupplier: parseUnsignedId(json['id_supplier']),
  idDefaultCategory: parseUnsignedId(json['id_category_default']),
  new_: stringFromDynamicJson(json['new']),
  cacheDefaultAttribute: stringFromDynamicJson(json['cache_default_attribute']),
  idDefaultImage: stringFromDynamicJson(json['id_default_image']),
  idDefaultCombination: stringFromDynamicJson(json['id_default_combination']),
  idTaxRulesGroup: parseUnsignedId(json['id_tax_rules_group']),
  positionInCategory: stringFromDynamicJson(json['position_in_category']),
  manufacturerName: stringFromDynamicJson(json['manufacturer_name']),
  quantity: stringFromDynamicJson(json['quantity']),
  type: stringFromDynamicJson(json['type']),
  idShopDefault: parseUnsignedId(json['id_shop_default']),
  reference: json['reference'] as String?,
  supplierReference: json['supplier_reference'] as String?,
  location: json['location'] as String?,
  width: parseIsFloat(json['width']),
  height: parseIsFloat(json['height']),
  depth: parseIsFloat(json['depth']),
  weight: parseIsFloat(json['weight']),
  quantityDiscount: parseIsBool(json['quantity_discount']),
  ean13: json['ean13'] as String?,
  isbn: json['isbn'] as String?,
  upc: json['upc'] as String?,
  mpn: json['mpn'] as String?,
  cacheIsPack: parseIsBool(json['cache_is_pack']),
  cacheHasAttachments: parseIsBool(json['cache_has_attachments']),
  isVirtual: parseIsBool(json['is_virtual']),
  state: parseUnsignedId(json['state']),
  additionalDeliveryTimes: parseUnsignedId(json['additional_delivery_times']),
  deliveryInStock: json['delivery_in_stock'] as String?,
  deliveryOutStock: json['delivery_out_stock'] as String?,
  onSale: parseIsBool(json['on_sale']),
  onlineOnly: parseIsBool(json['online_only']),
  ecotax: parseIsFloat(json['ecotax']),
  minimalQuantity: parseUnsignedId(json['minimal_quantity']),
  lowStockThreshold: stringFromJson(json['low_stock_threshold'] as String?),
  lowStockAlert: parseIsBool(json['low_stock_alert']),
  price: parseIsFloat(json['price']),
  wholesalePrice: parseIsFloat(json['wholesale_price']),
  unity: stringFromJson(json['unity'] as String?),
  unitPriceRatio: stringFromDynamicJson(json['unit_price_ratio']),
  additionalShippingCost: parseIsFloat(json['additional_shipping_cost']),
  customizable: parseUnsignedId(json['customizable']),
  textFields: parseUnsignedId(json['text_fields']),
  uploadableFiles: parseUnsignedId(json['uploadable_files']),
  active: parseIsBool(json['active']),
  redirectType: json['redirect_type'] as String?,
  idTypeRedirected: parseUnsignedId(json['id_type_redirected']),
  availableForOrder: parseIsBool(json['available_for_order']),
  availableDate: parseIsDate(json['available_date']),
  showCondition: parseIsBool(json['show_condition']),
  condition: json['condition'] as String?,
  showPrice: parseIsBool(json['show_price']),
  indexed: parseIsBool(json['indexed']),
  visibility: json['visibility'] as String?,
  advancedStockManagement: parseIsBool(json['advanced_stock_management']),
  dateAdd: parseIsDate(json['date_add']),
  dateUpd: parseIsDate(json['date_upd']),
  packStockType: parseUnsignedId(json['pack_stock_type']),
  metaDescription: json['meta_description'] as String?,
  metaKeywords: json['meta_keywords'] as String?,
  metaTitle: json['meta_title'] as String?,
  linkRewrite: json['link_rewrite'] as String?,
  name: json['name'] as String?,
  description: json['description'] as String?,
  descriptionShort: json['description_short'] as String?,
  availableNow: json['available_now'] as String?,
  availableLater: json['available_later'] as String?,
  priceTaxIncluded: json['price_tax_incl'] as String?,
  priceTaxExcluded: json['price_tax_excl'] as String?,
  associations: _associationsDTOFromJson(json['associations']),
);

Map<String, dynamic> _$ProductDTOToJson(
  _ProductDTO instance,
) => <String, dynamic>{
  'id': instance.id,
  'id_manufacturer': instance.idManufacturer,
  'id_supplier': instance.idSupplier,
  'id_category_default': instance.idDefaultCategory,
  'new': instance.new_,
  'cache_default_attribute': instance.cacheDefaultAttribute,
  'id_default_image': instance.idDefaultImage,
  'id_default_combination': instance.idDefaultCombination,
  'id_tax_rules_group': instance.idTaxRulesGroup,
  'position_in_category': instance.positionInCategory,
  'manufacturer_name': instance.manufacturerName,
  'quantity': instance.quantity,
  'type': instance.type,
  'id_shop_default': instance.idShopDefault,
  'reference': instance.reference,
  'supplier_reference': instance.supplierReference,
  'location': instance.location,
  'width': instance.width,
  'height': instance.height,
  'depth': instance.depth,
  'weight': instance.weight,
  'quantity_discount': isBoolToJson(instance.quantityDiscount),
  'ean13': instance.ean13,
  'isbn': instance.isbn,
  'upc': instance.upc,
  'mpn': instance.mpn,
  'cache_is_pack': isBoolToJson(instance.cacheIsPack),
  'cache_has_attachments': isBoolToJson(instance.cacheHasAttachments),
  'is_virtual': isBoolToJson(instance.isVirtual),
  'state': instance.state,
  'additional_delivery_times': instance.additionalDeliveryTimes,
  'delivery_in_stock': instance.deliveryInStock,
  'delivery_out_stock': instance.deliveryOutStock,
  'on_sale': isBoolToJson(instance.onSale),
  'online_only': isBoolToJson(instance.onlineOnly),
  'ecotax': isFloatToJson(instance.ecotax),
  'minimal_quantity': instance.minimalQuantity,
  'low_stock_threshold': instance.lowStockThreshold,
  'low_stock_alert': isBoolToJson(instance.lowStockAlert),
  'price': isFloatToJson(instance.price),
  'wholesale_price': isFloatToJson(instance.wholesalePrice),
  'unity': instance.unity,
  'unit_price_ratio': instance.unitPriceRatio,
  'additional_shipping_cost': isFloatToJson(instance.additionalShippingCost),
  'customizable': instance.customizable,
  'text_fields': instance.textFields,
  'uploadable_files': instance.uploadableFiles,
  'active': isBoolToJson(instance.active),
  'redirect_type': instance.redirectType,
  'id_type_redirected': instance.idTypeRedirected,
  'available_for_order': isBoolToJson(instance.availableForOrder),
  'available_date': instance.availableDate?.toIso8601String(),
  'show_condition': isBoolToJson(instance.showCondition),
  'condition': instance.condition,
  'show_price': isBoolToJson(instance.showPrice),
  'indexed': isBoolToJson(instance.indexed),
  'visibility': instance.visibility,
  'advanced_stock_management': isBoolToJson(instance.advancedStockManagement),
  'date_add': instance.dateAdd?.toIso8601String(),
  'date_upd': instance.dateUpd?.toIso8601String(),
  'pack_stock_type': instance.packStockType,
  'meta_description': instance.metaDescription,
  'meta_keywords': instance.metaKeywords,
  'meta_title': instance.metaTitle,
  'link_rewrite': instance.linkRewrite,
  'name': instance.name,
  'description': instance.description,
  'description_short': instance.descriptionShort,
  'available_now': instance.availableNow,
  'available_later': instance.availableLater,
  'price_tax_incl': instance.priceTaxIncluded,
  'price_tax_excl': instance.priceTaxExcluded,
  'associations': instance.associations,
};
